// Generated by CoffeeScript 1.8.0
var handleLink, handlePath, route_url, timeouts, turnOnFireflies;

handleLink = function() {
  return $('a').off('click').on('click', function(e) {
    var $el, href, path;
    $el = $(e.currentTarget);
    href = $el.attr('href');
    if (href[0] !== '/') {
      return;
    }
    e.preventDefault();
    path = url('path', href);
    route_url(path || '/');
    return false;
  });
};

timeouts = [];

turnOnFireflies = function() {
  if (window.fireflies_on) {
    return;
  }
  initialize();
  setInterval(draw, rint);
  $(window).off('resize').on('resize', initialize);
  return window.fireflies_on = true;
};

handlePath = function(path, $base_el) {
  var $el, $spans;
  while (timeouts.length) {
    clearTimeout(timeouts.pop());
  }
  switch (path) {
    case '/':
      $el = $base_el.find('.rewrite');
      $base_el.find('.additions').remove();
      $el.lettering();
      $spans = $el.find('> span');
      return async.eachLimit($spans, 2, (function(char, next) {
        var $char, height, width, x, y;
        $char = $(char);
        width = window.innerWidth / 3;
        height = window.innerHeight / 3;
        x = Math.random() * width - width / 2;
        y = Math.random() * height - height / 2;
        $char.attr({
          'style': "left: " + x + "px; top: " + y + "px;"
        });
        return timeouts.push(setTimeout((function() {
          $char.addClass('show');
          return next();
        }), 400));
      }), function() {
        var $sub;
        $sub = $('<div class = "additions"> Welcome to Our Wedding Website </div>');
        $base_el.append($sub);
        return timeouts.push(setTimeout((function() {
          return $sub.fadeIn('slow', function() {
            return turnOnFireflies();
          });
        }), 1000));
      });
    default:
      return turnOnFireflies();
  }
};

route_url = function(path) {
  var $el, $link, data, new_path;
  $('#body').attr('class', '');
  path = path || url('path');
  data = path.split('/');
  history.replaceState(null, null, path);
  new_path = "/" + (data[1] || '');
  $("[data-route]").hide();
  $el = $("[data-route='" + new_path + "']");
  handlePath(new_path, $el);
  $el.fadeIn();
  $link = $("#navigation a[href='" + new_path + "']");
  $link.addClass('active');
  return $link.siblings().removeClass('active');
};

handleLink();

$(window).load(function() {
  return route_url();
});
